## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1
  - nightly
notifications:
  email: false

env:
  global:
  - PANDOC=~/.pandoc
  - PANDOC_DEB="https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb"

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

cache:
  directories:
    - $PANDOC

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pandoc; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if [[ ! -f "$PANDOC/pandoc.deb" ]]; then curl -L "$PANDOC_DEB" > "$PANDOC/pandoc.deb" && dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"; fi ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$PANDOC/usr/bin:$PATH"; fi

## uncomment the following lines to override the default test script
script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - julia --project --color=yes -e "import Pkg; Pkg.instantiate(); Pkg.build();"
  - julia --check-bounds=yes --depwarn=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"
  - kill %1

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Presentation")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.build("Presentation"); Pkg.instantiate()'
        - DOCUMENTER_DEBUG=true julia --project=docs/ docs/make.jl
      after_success: skip


